services:
  today:
    build: .
    image: today
    command: python main.py
    restart: unless-stopped
    ports:
      - 8008:8008
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]