app:
  host: 0.0.0.0
  port: 8005
  diarization: false
  warmup-file: warmup_file
  transcription: true
  sample_rate: 16000
  channels: 1
  bytes_per_sample: 2
  max_bytes_per_sec: 32000 * 5

  prompts:
    convert_to_diary: |
      You are a very talented diary typing 
      Convert the following text into a diary-style entry while correcting any grammar, spelling, and punctuation mistakes. 
      Do not add or remove any words beyond necessary corrections.

      here is the diary of the user:
      {context}

    correct_grammer_mistakes: |
      Correct the grammar of the following 
      text:{context}
      Corrected version:
