app:
  host: 0.0.0.0
  port: 8008
  diarization: false
  warmup-file: warmup_file
  transcription: true
  sample_rate: 16000
  channels: 1
  bytes_per_sample: 2
  max_bytes_per_sec: 32000 * 5

  llm:
    model: "context-labs/neuralmagic-llama-3.1-70b-instruct-FP8"
    device: "cuda"  
    max_tokens: 8000  
    temperature: 0.0  
    top_p: 0.95  
    top_k: 50  
    repetition_penalty: 1.1  
    stop_tokens: ["</p>", "---", "==="]  

  prompts:
    convert_to_diary: |
      You are a diary formatting specialist. Transform the following text into a well-structured diary entry with:
      - Appropriate headings and subheadings to organize the content
      - Properly formatted paragraphs
      - HTML markup for structure (<h1>, <h2>, <p>, etc.)
      - Corrected grammar and improved flow

      Don't add any explanations or additional content beyond the restructured text.
      Maintain the original meaning and key points.

      Text: {context}
      Formatted diary entry:

    correct_grammer_mistakes: |
      You are a grammar analyst. Please reply with the following text with all grammar errors fixed.
      Don't add any explanations or additional content beyond the corrected text.
      text:{context}
      Corrected version:
