app:
  host: 0.0.0.0
  port: 8008
  diarization: false
  warmup-file: warmup_file
  transcription: true
  sample_rate: 16000
  channels: 1
  bytes_per_sample: 2
  max_bytes_per_sec: 32000 * 5

  llm:
    model: "mistralai/Mistral-7B-Instruct-v0.2"  # Model to use
    device: "cuda"  # Device to run on (cuda/cpu)
    max_tokens: 1024  # Maximum tokens to generate
    temperature: 0.0  # Temperature for generation (0.0 for deterministic)
    top_p: 0.95  # Top-p sampling parameter
    top_k: 50  # Top-k sampling parameter
    repetition_penalty: 1.1  # Penalty for repeating tokens
    stop_tokens: ["</p>", "---", "==="]  # Tokens that stop generation

  prompts:
    convert_to_diary: |
      You are a diary formatting specialist. Transform the following text into a well-structured diary entry with:
      - Appropriate headings and subheadings to organize the content
      - Properly formatted paragraphs
      - HTML markup for structure (<h1>, <h2>, <p>, etc.)
      - Corrected grammar and improved flow

      Don't add any explanations or additional content beyond the restructured text.
      Maintain the original meaning and key points.

      Text: {context}
      Formatted diary entry:

    correct_grammer_mistakes: |
      You are a grammar analyst. Please reply with the following text with all grammar errors fixed.
      Don't add any explanations or additional content beyond the corrected text.
      text:{context}
      Corrected version:
